# Generated by Django 4.2.15 on 2024-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0002_conversation_delete_chatbots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('binary_content', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
