# Generated by Django 5.1.1 on 2024-11-06 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0003_scrapeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('License_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('License_Name', models.CharField(max_length=255)),
                ('License_Valid', models.BooleanField()),
                ('LicenseValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DocDescription', models.CharField(max_length=255)),
                ('DocLink', models.CharField(max_length=255)),
                ('LastDateScraped', models.DateField()),
                ('DocName', models.CharField(max_length=255)),
                ('RequiresAttribution', models.BooleanField()),
                ('DocValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.license')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('Answer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Link', models.CharField(max_length=255, null=True)),
                ('PageNum', models.IntegerField()),
                ('Answer', models.CharField(max_length=255)),
                ('LastDayScraped', models.DateField()),
                ('CopyrightDate', models.DateField()),
                ('OutdatedFlag', models.IntegerField(blank=True, null=True)),
                ('FlagNewAnswerID', models.IntegerField(blank=True, null=True)),
                ('AnswerRating', models.IntegerField(blank=True, null=True)),
                ('AnswerValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('Doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.document')),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.license')),
                ('Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('RevAnswer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ScoreScale', models.IntegerField(help_text='Rating between 1 (worst) and 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Description', models.CharField(help_text='Brief description of the answer', max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.question')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('SourceID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('SourceName', models.CharField(max_length=255)),
                ('SourceDescription', models.CharField(max_length=255)),
                ('SourceLink', models.CharField(max_length=255)),
                ('SourceValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.license')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='Source_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_be.source'),
        ),
    ]
