# Generated by Django 5.1.1 on 2024-11-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0004_license_question_reviewer_document_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='CopyrightDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='PageNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
