# Generated by Django 4.2.18 on 2025-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0005_alter_answer_copyrightdate_alter_answer_pagenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('large_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
