# Generated by Django 4.2.18 on 2025-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0006_document_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
