# Generated by Django 4.2.18 on 2025-02-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0007_scrapeddata_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedDataMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField()),
                ('scraped_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chatbot_be.scrapeddata')),
            ],
        ),
    ]
